### ISSUE TITLE
RangeError: Maximum BigInt size exceeded

### ISSUE THREAD

**Issue by prestonvanloon** [crytic/evm-opcodes#9]
```
(node:3067) UnhandledPromiseRejectionWarning: RangeError: Maximum BigInt size exceeded
    at eval (eval at <anonymous> (/tmp/test/node_modules/evm/lib/EVM.node.js:1:12359), <anonymous>:1:9)
    at NativeBigInt.pow (/tmp/test/node_modules/evm/lib/EVM.node.js:1:12653)
    at Object.d.default [as EXP] (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10281826)
    at g.parse (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10273112)
    at Object.d.default [as JUMPI] (/tmp/test/node_modules/evm/lib/EVM.node.js:1:6408475)
    at g.parse (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10273112)
    at Object.d.default [as JUMPI] (/tmp/test/node_modules/evm/lib/EVM.node.js:1:6408475)
    at g.parse (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10273112)
    at Object.d.default [as JUMPI] (/tmp/test/node_modules/evm/lib/EVM.node.js:1:6408517)
    at g.parse (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10273112)
    at Object.d.default [as JUMPI] (/tmp/test/node_modules/evm/lib/EVM.node.js:1:6408475)
    at g.parse (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10273112)
    at g.decompile (/tmp/test/node_modules/evm/lib/EVM.node.js:1:10273172)
    at web3.eth.getCode.then.code (/tmp/test/index.js:9:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

To reproduce:

```javascript
const { EVM } = require("evm");
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider("https://goerli.prylabs.net"));

web3.eth.getCode("0xB880162F8b188E9D7b075081f6E38fc3657ae10e").then(code => {  /* ETH2 deposit contract */
    const evm = new EVM(code);
    console.log(evm.getFunctions());  /* Get functions */
    console.log(evm.getEvents());  /* Get events */
    console.log(evm.decompile());  /* Decompile bytecode */
});
```

**Comment by prestonvanloon** [comment]
Wrong repo! Sorry
